# Generated by Django 4.2.5 on 2023-09-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
